In [16]:
# importing the required libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
import os
import joblib
from sklearn.preprocessing import MinMaxScaler

In [17]:
combined_df = pd.read_csv("../data/customer_features.csv")

In [18]:
combined_df.head()

,customer_id,gender,age,tenure,monthlycharges,paymentmethod,churn,industry
0,TEL_7590-VHVEG,Female,39,1,29.85,Electronic check,0.0,Telecom
1,TEL_5575-GNVDE,Male,43,34,56.95,Mailed check,0.0,Telecom
2,TEL_3668-QPYBK,Male,24,2,53.85,Mailed check,1.0,Telecom
3,TEL_7795-CFOCW,Male,23,45,42.30,Bank transfer (automatic),0.0,Telecom
4,TEL_9237-HQITU,Female,21,2,70.70,Electronic check,1.0,Telecom

In [19]:
# Dictionary to store the mapping (original value: encoded number) for each column
mappings = {}

name_encoder = LabelEncoder()
for col in ['gender', 'paymentmethod', 'industry']:
    # Fit and transform the current column
    combined_df[col] = name_encoder.fit_transform(combined_df[col])

    # Store the mapping *before* the encoder is overwritten in the next iteration
    # Create a dictionary mapping the original class names (classes_) to their index (0, 1, 2, ...)
    class_names = name_encoder.classes_
    mapping = {class_names[i]: i for i in range(len(class_names))}
    mappings[col] = mapping
    
    print(f"\n--- Mapping for '{col}' ---")
    print(mapping)

# Access the mapping later
print("\n--- Final Mappings Dictionary ---")
print(mappings['gender'])
# Example: Check which value is 0 for 'gender'
# Note: You can reverse the dictionary if you want to check 0 = ?

--- Mapping for 'gender' ---
{'Female': 0, 'Male': 1}

--- Mapping for 'paymentmethod' ---
{'Bank transfer (automatic)': 0, 'Cash on Delivery': 1, 'Credit Card': 2, 'Credit card (automatic)': 3, 'Debit Card': 4, 'Electronic check': 5, 'Mailed check': 6, 'Net Banking': 7, 'PayPal': 8, 'UPI': 9}

--- Mapping for 'industry' ---
{'Ecommerce': 0, 'Subscription': 1, 'Telecom': 2}

--- Final Mappings Dictionary ---
{'Female': 0, 'Male': 1}

In [20]:
combined_df.head()

,customer_id,gender,age,tenure,monthlycharges,paymentmethod,churn,industry
0,TEL_7590-VHVEG,0,39,1,29.85,5,0.0,2
1,TEL_5575-GNVDE,1,43,34,56.95,6,0.0,2
2,TEL_3668-QPYBK,1,24,2,53.85,6,1.0,2
3,TEL_7795-CFOCW,1,23,45,42.30,0,0.0,2
4,TEL_9237-HQITU,0,21,2,70.70,5,1.0,2

In [21]:
save_path = "../models"
os.makedirs(save_path, exist_ok=True)

In [22]:
# saving name_encoder

try:
    joblib.dump(name_encoder, os.path.join(save_path, "name_encoder.pkl"))
    print("Encoder saved")
except Exception as e:
    print("Encoder not found or not saved")

Encoder saved

In [24]:
# saving the mappings 
joblib.dump(mappings, "../models/mappings.pkl")

['../models/mappings.pkl']

#Load mappings inside backend:


mappings = joblib.load("backend/artifacts/mappings.pkl")

gender_map = {v: k for k, v in mappings["gender"].items()}
payment_method_map = {v: k for k, v in mappings["paymentmethod"].items()}
industry_map = {v: k for k, v in mappings["industry"].items()}